const products=[
 {id:'iphone-16-pro-256-black',name:'iPhone 16 Pro',memory:'۲۵۶GB',color:'Titanium Black',category:'iPhone',price:1549000000,region:'CH/A',note:'قدرت حرفه‌ای، طراحی تیتانیوم.'},
 {id:'iphone-16-pro-max-256-black',name:'iPhone 16 Pro Max',memory:'۲۵۶GB',color:'Titanium Black',category:'iPhone',price:1699000000,region:'CH/A',note:'بزرگ‌ترین نمایشگر و باتری.'},
 {id:'iphone-16-256-blue',name:'iPhone 16',memory:'۲۵۶GB',color:'Ultramarine',category:'iPhone',price:1199000000,region:'CH/A',note:'انتخاب هوشمند برای هر روز.'},
 {id:'airpods-pro-2',name:'AirPods Pro 2',memory:'—',color:'White',category:'AirPods',price:329000000,region:'Global',note:'صدای فراگیر و حذف نویز.'}
];
const fmt=new Intl.NumberFormat('fa-IR');
const get=(key,fallback=[])=>{try{return JSON.parse(localStorage.getItem(key))||fallback}catch{return fallback}};
const put=(key,value)=>localStorage.setItem(key,JSON.stringify(value));
const toast=(text)=>{let el=document.querySelector('.toast-store');if(!el){el=document.createElement('div');el.className='toast-store';document.body.append(el)}el.textContent=text;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2400)};
function card(product){const wished=get('apple333-wishlist').includes(product.id);return `<article class="product-card"><button class="wish" data-wish="${product.id}" aria-label="افزودن ${product.name} به علاقه‌مندی‌ها">${wished?'♥':'♡'}</button><a href="product.html?id=${product.id}"><div class="visual"><i></i></div><h2>${product.name}</h2><small>${product.memory} · ${product.color}</small><p class="price">${fmt.format(product.price)} ریال</p></a><div class="card-actions"><button class="outline" data-compare="${product.id}">مقایسه</button><button class="dark" data-cart="${product.id}">افزودن به سبد</button></div></article>`}
function renderCatalog(){const root=document.querySelector('#product-grid');if(!root)return;const query=(document.querySelector('#search')?.value||'').toLowerCase();const category=document.querySelector('#category')?.value||'all';const max=Number(document.querySelector('#price')?.value||2000000000);const visible=products.filter(p=>(category==='all'||p.category===category)&&(p.name.toLowerCase().includes(query)||p.category.toLowerCase().includes(query))&&p.price<=max);root.innerHTML=visible.map(card).join('')||'<div class="empty-card">محصولی با این فیلتر پیدا نشد.</div>';document.querySelector('#result-count').textContent=`${fmt.format(visible.length)} محصول`}
function renderProduct(){const host=document.querySelector('#product-detail');if(!host)return;const target=new URLSearchParams(location.search).get('id');const p=products.find(x=>x.id===target)||products[0];host.innerHTML=`<section class="product-layout"><div class="gallery" aria-label="گالری ${p.name}"><div class="hero-device"></div></div><div><article class="detail-card"><p class="kicker">${p.category.toUpperCase()}</p><h1>${p.name}</h1><p>${p.note}</p><p class="price">${fmt.format(p.price)} ریال</p><h2>رنگ</h2><div class="choice"><button aria-pressed="true">${p.color}</button><button aria-pressed="false">Natural Titanium</button></div><h2 style="margin-top:22px">ظرفیت</h2><div class="choice"><button aria-pressed="true">${p.memory}</button><button aria-pressed="false">۵۱۲GB</button></div></article><article class="detail-card"><h2>تحویل و موجودی</h2><div class="availability"><span>انبار مرکزی</span><span class="available">موجود برای ارسال</span></div><div class="availability"><span>شعبه ونک</span><span class="available">موجود برای تحویل حضوری</span></div><div class="availability"><span>خرید اقساطی</span><a href="checkout.html">محاسبه شرایط ←</a></div><div class="detail-actions"><button class="buy" data-cart="${p.id}">افزودن به سبد</button><button class="outline" data-compare="${p.id}">مقایسه</button></div></article><article class="detail-card"><h2>مشخصات کلیدی</h2><div class="availability"><span>نمایشگر</span><b>Super Retina XDR</b></div><div class="availability"><span>تراشه</span><b>A18 Pro</b></div><div class="availability"><span>ریجن</span><b>${p.region}</b></div></article></div></section>`}
function renderCompare(){const root=document.querySelector('#compare-root');if(!root)return;const ids=get('apple333-compare');const selected=products.filter(p=>ids.includes(p.id));if(!selected.length){root.innerHTML='<div class="empty-card">برای مقایسه، حداکثر چهار محصول را از صفحهٔ فروشگاه انتخاب کنید.</div>';return}const rows=[['حافظه','memory'],['رنگ','color'],['ریجن','region'],['قیمت','price'],['نمایشگر',null],['پردازنده',null]];root.innerHTML=`<div class="compare-table"><table><thead><tr><th>مشخصات</th>${selected.map(p=>`<th>${p.name}<br><button class="outline" data-compare="${p.id}">حذف</button></th>`).join('')}</tr></thead><tbody>${rows.map(([label,key])=>`<tr><td class="spec">${label}</td>${selected.map(p=>`<td>${key==='price'?fmt.format(p.price)+' ریال':key?p[key]:label==='نمایشگر'?'Super Retina XDR':'Apple Silicon'}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`}
function renderWishlist(){const root=document.querySelector('#wishlist-root');if(!root)return;const selected=products.filter(p=>get('apple333-wishlist').includes(p.id));root.innerHTML=selected.length?`<div class="product-grid">${selected.map(card).join('')}</div>`:'<div class="empty-card">هنوز محصولی را ذخیره نکرده‌اید.</div>'}
function updateCounts(){const compare=get('apple333-compare').length,wish=get('apple333-wishlist').length,cart=get('apple333-cart').length;document.querySelectorAll('[data-count=compare]').forEach(e=>e.textContent=compare);document.querySelectorAll('[data-count=wishlist]').forEach(e=>e.textContent=wish);document.querySelectorAll('[data-count=cart]').forEach(e=>e.textContent=cart)}
document.addEventListener('click',e=>{const id=e.target.dataset.cart||e.target.dataset.wish||e.target.dataset.compare;if(!id)return;const type=e.target.dataset.cart?'cart':e.target.dataset.wish?'wishlist':'compare';let values=get(`apple333-${type}`);if(values.includes(id)){values=values.filter(x=>x!==id);toast('از فهرست حذف شد')}else{if(type==='compare'&&values.length===4)return toast('حداکثر ۴ محصول قابل مقایسه است');values.push(id);toast(type==='cart'?'به سبد اضافه شد':type==='wishlist'?'به علاقه‌مندی‌ها اضافه شد':'به مقایسه اضافه شد')}put(`apple333-${type}`,values);updateCounts();if(document.body.dataset.page==='catalog')renderCatalog();if(document.body.dataset.page==='wishlist')renderWishlist();if(document.body.dataset.page==='compare')renderCompare()});
document.querySelector('#search')?.addEventListener('input',renderCatalog);document.querySelector('#category')?.addEventListener('change',renderCatalog);document.querySelector('#price')?.addEventListener('input',renderCatalog);renderCatalog();renderProduct();renderCompare();renderWishlist();updateCounts();
