import { expect, test, type Page } from "@playwright/test";
import AxeBuilder from "@axe-core/playwright";

import {
  ORDER_E2E_ACTORS,
  ORDER_E2E_FIXTURES,
  ORDER_E2E_PASSWORD,
} from "../../scripts/order-e2e-fixtures.mjs";

type ApiEnvelope<T> = Readonly<{
  success: boolean;
  data?: T;
  error?: Readonly<{ code?: string; message?: string }>;
}>;

type Order = Readonly<{
  id: string;
  orderNumber: string;
  version: number;
  status: string;
  paymentStatus: string;
  allocationStatus: string;
  fulfillmentStatus: string;
  fulfillment?: Readonly<{ status: string }> | null;
}>;

let primaryOrder: Order | null = null;

function requestKey(operation: string): string {
  return `e2e-phase07-${operation}-${crypto.randomUUID()}`;
}

function requestPayload(response: import("@playwright/test").Response): {
  idempotencyKey: string;
  [key: string]: unknown;
} {
  const rawPayload = response.request().postData();
  expect(rawPayload).toBeTruthy();
  const payload = JSON.parse(rawPayload ?? "{}") as Record<string, unknown>;
  expect(typeof payload.idempotencyKey).toBe("string");
  expect(response.request().headers()["idempotency-key"]).toBe(
    payload.idempotencyKey,
  );
  return payload as { idempotencyKey: string; [key: string]: unknown };
}

async function login(
  page: Page,
  actor: (typeof ORDER_E2E_ACTORS)[keyof typeof ORDER_E2E_ACTORS],
  callbackUrl: string,
): Promise<void> {
  await page.goto(
    `/account/login?callbackUrl=${encodeURIComponent(callbackUrl)}`,
  );
  await page.locator('input[name="email"]').fill(actor.email);
  await page.locator('input[name="password"]').fill(ORDER_E2E_PASSWORD);
  await Promise.all([
    page.waitForURL(new RegExp(callbackUrl.replaceAll("/", "\\/")), {
      timeout: 20_000,
    }),
    page.locator('button[type="submit"]').click(),
  ]);
}

async function browserApi<T>(
  page: Page,
  path: string,
  init?: Readonly<{ method?: string; body?: unknown; idempotencyKey?: string }>,
): Promise<Readonly<{ status: number; body: ApiEnvelope<T> }>> {
  return page.evaluate(
    async ({ requestedPath, requestedInit }) => {
      const headers = new Headers({
        "x-request-id": `e2e-phase07-${crypto.randomUUID()}`,
        accept: "application/json",
      });
      if (requestedInit?.body !== undefined)
        headers.set("content-type", "application/json");
      if (requestedInit?.idempotencyKey)
        headers.set("idempotency-key", requestedInit.idempotencyKey);
      const response = await fetch(requestedPath, {
        method: requestedInit?.method ?? "GET",
        headers,
        ...(requestedInit?.body === undefined
          ? {}
          : { body: JSON.stringify(requestedInit.body) }),
      });
      return { status: response.status, body: await response.json() };
    },
    { requestedPath: path, requestedInit: init },
  ) as Promise<Readonly<{ status: number; body: ApiEnvelope<T> }>>;
}

function requireOrder(
  result: Readonly<{ status: number; body: ApiEnvelope<Order> }>,
  expectedStatus: number,
): Order {
  expect(result.status).toBe(expectedStatus);
  expect(result.body.success).toBe(true);
  expect(result.body.data).toBeDefined();
  return result.body.data!;
}

async function requireOrderResponse(
  response: import("@playwright/test").Response,
  expectedStatus: number,
): Promise<Order> {
  return requireOrder(
    {
      status: response.status(),
      body: (await response.json()) as ApiEnvelope<Order>,
    },
    expectedStatus,
  );
}

async function addProductToCart(page: Page): Promise<void> {
  await page.goto(`/products/${ORDER_E2E_FIXTURES.product.slug}`);
  const intendedVariant = page.getByRole("button", { name: /256GB Black/ });
  await expect(intendedVariant).toBeVisible();
  await intendedVariant.click();
  const addToCart = page.getByTestId("storefront-add-to-cart");
  await expect(addToCart).toBeEnabled();
  const [cartResponse] = await Promise.all([
    page.waitForResponse(
      (response) =>
        response.url().includes("/api/store/cart/items") &&
        response.request().method() === "POST",
    ),
    addToCart.click(),
  ]);
  expect(cartResponse.status()).toBe(201);
}

/**
 * Drive the actual checkout UI. The replay assertion deliberately reuses the
 * idempotency key generated by the user-facing form rather than inventing a
 * separate API-only request key.
 */
async function createCustomerOrderThroughUi(page: Page): Promise<Order> {
  await addProductToCart(page);
  await login(page, ORDER_E2E_ACTORS.CUSTOMER, "/checkout");
  await page.goto("/checkout");

  const shippingAddress = page.getByRole("combobox").first();
  await expect(shippingAddress).toBeVisible();
  await shippingAddress.selectOption(ORDER_E2E_FIXTURES.customerAddress.id);

  const [quoteResponse] = await Promise.all([
    page.waitForResponse(
      (response) =>
        new URL(response.url()).pathname === "/api/store/checkout/quote" &&
        response.request().method() === "POST",
    ),
    page.getByRole("button", { name: /دریافت پیش‌نمایش خرید/ }).click(),
  ]);
  expect(quoteResponse.status()).toBe(200);

  const [createResponse] = await Promise.all([
    page.waitForResponse(
      (response) =>
        new URL(response.url()).pathname === "/api/store/orders" &&
        response.request().method() === "POST",
    ),
    page.getByRole("button", { name: /ثبت امن سفارش/ }).click(),
  ]);
  const created = await requireOrderResponse(createResponse, 201);
  const payload = requestPayload(createResponse);

  await expect(page).toHaveURL(
    new RegExp(`/checkout/success/${encodeURIComponent(created.orderNumber)}$`),
  );
  await expect(page.getByTestId("customer-order-detail")).toBeVisible();

  const replay = requireOrder(
    await browserApi<Order>(page, "/api/store/orders", {
      method: "POST",
      idempotencyKey: payload.idempotencyKey,
      body: payload,
    }),
    201,
  );
  expect(replay.id).toBe(created.id);
  expect(replay.orderNumber).toBe(created.orderNumber);
  return created;
}

async function advanceFulfillment(
  page: Page,
  order: Order,
  status: "PENDING" | "PICKING" | "PACKED" | "SHIPPED" | "DELIVERED",
): Promise<Order> {
  const idempotencyKey = requestKey(`fulfillment-${status.toLowerCase()}`);
  const result = await browserApi<Order>(
    page,
    `/api/admin/orders/${order.id}/fulfillments`,
    {
      method: "POST",
      idempotencyKey,
      body: {
        method: "DELIVERY",
        status,
        ...(status === "SHIPPED"
          ? { trackingCode: "E2E-PHASE07-TRACKING" }
          : {}),
        expectedVersion: order.version,
        idempotencyKey,
      },
    },
  );
  return requireOrder(result, 200);
}

test.describe("Phase 07 order-management browser journeys", () => {
  test.describe.configure({ mode: "serial" });

  test("protects customer and admin order routes before authentication", async ({
    page,
  }) => {
    await page.goto("/account/orders");
    await expect(page).toHaveURL(/\/account\/login/);
    await page.goto("/admin/orders");
    await expect(page).toHaveURL(/\/account\/login/);
  });

  test("creates a customer order through checkout UI, renders success, and replays the UI-generated request safely", async ({
    page,
  }) => {
    const created = await createCustomerOrderThroughUi(page);
    primaryOrder = created;
    expect(created.status).toBe("PENDING_CONFIRMATION");
    expect(created.allocationStatus).toBe("ALLOCATED");
    await expect(page.getByTestId("customer-order-detail")).toContainText(
      created.orderNumber,
    );
    await page.goto("/account/orders");
    await expect(page.getByTestId("customer-order-list")).toContainText(
      created.orderNumber,
    );
  });

  test("denies customer access to the administrative order surface", async ({
    page,
  }) => {
    expect(primaryOrder).not.toBeNull();
    await login(page, ORDER_E2E_ACTORS.CUSTOMER, "/account/orders");
    const result = await browserApi<unknown>(
      page,
      `/api/admin/orders/${primaryOrder!.id}`,
    );
    expect(result.status).toBe(403);
    expect(result.body.success).toBe(false);
  });

  test("does not allow a different customer to retrieve another customer’s order by order number", async ({
    page,
  }) => {
    expect(primaryOrder).not.toBeNull();
    await login(page, ORDER_E2E_ACTORS.CUSTOMER_OTHER, "/account/orders");
    const result = await browserApi<unknown>(
      page,
      `/api/store/orders/${encodeURIComponent(primaryOrder!.orderNumber)}`,
    );
    expect(result.status).toBe(403);
    expect(result.body.success).toBe(false);
  });

  test("lets an authorized manager confirm and fulfill while rejecting legacy manual payment", async ({
    page,
  }) => {
    expect(primaryOrder).not.toBeNull();
    await login(page, ORDER_E2E_ACTORS.ORDER_MANAGER, "/admin/orders");

    const search = page.getByPlaceholder(/شماره سفارش، نام، ایمیل یا موبایل/);
    await search.fill(primaryOrder!.orderNumber);
    const orderLink = page.getByRole("link", {
      name: primaryOrder!.orderNumber,
    });
    await expect(orderLink).toBeVisible();
    await orderLink.click();
    await expect(page).toHaveURL(
      new RegExp(`/admin/orders/${primaryOrder!.id}$`),
    );
    await expect(page.getByTestId("admin-order-detail")).toBeVisible();

    const detail = requireOrder(
      await browserApi<Order>(page, `/api/admin/orders/${primaryOrder!.id}`),
      200,
    );
    const invalidCreate = await browserApi<unknown>(page, "/api/admin/orders", {
      method: "POST",
      idempotencyKey: requestKey("invalid-admin-create"),
      body: {
        source: "ADMIN",
        idempotencyKey: requestKey("different-invalid-key"),
      },
    });
    expect(invalidCreate.status).toBe(400);
    expect(invalidCreate.body.success).toBe(false);

    const allocationKey = requestKey("allocation-primary");
    const allocation = requireOrder(
      await browserApi<Order>(page, `/api/admin/orders/${detail.id}/allocate`, {
        method: "POST",
        idempotencyKey: allocationKey,
        body: {
          expectedVersion: detail.version,
          idempotencyKey: allocationKey,
        },
      }),
      200,
    );
    expect(allocation.id).toBe(detail.id);
    expect(allocation.allocationStatus).toBe("ALLOCATED");

    await page.reload();
    await expect(page.getByTestId("admin-order-detail")).toBeVisible();
    await page.getByRole("button", { name: /تأیید سفارش/ }).click();
    const dialog = page.getByRole("dialog");
    await expect(dialog).toBeVisible();
    const [confirmResponse] = await Promise.all([
      page.waitForResponse(
        (response) =>
          new URL(response.url()).pathname ===
            `/api/admin/orders/${allocation.id}/confirm` &&
          response.request().method() === "POST",
      ),
      dialog.getByRole("button", { name: /تأیید نهایی/ }).click(),
    ]);
    const confirmed = await requireOrderResponse(confirmResponse, 200);
    const confirmPayload = requestPayload(confirmResponse);
    expect(confirmed.status).toBe("CONFIRMED");
    const confirmReplay = requireOrder(
      await browserApi<Order>(page, `/api/admin/orders/${detail.id}/confirm`, {
        method: "POST",
        idempotencyKey: confirmPayload.idempotencyKey,
        body: confirmPayload,
      }),
      200,
    );
    expect(confirmReplay.version).toBe(confirmed.version);

    let current = await advanceFulfillment(page, confirmed, "PENDING");
    const paymentKey = requestKey("payment-primary");
    const legacyPayment = await browserApi<Order>(
      page,
      `/api/admin/orders/${current.id}/payment`,
      {
        method: "POST",
        idempotencyKey: paymentKey,
        body: {
          provider: "E2E_MANUAL",
          method: "CARD_ON_DELIVERY",
          expectedVersion: current.version,
          idempotencyKey: paymentKey,
        },
      },
    );
    expect(legacyPayment.status).toBe(410);
    expect(legacyPayment.body.success).toBe(false);
    expect(legacyPayment.body.error?.code).toBe(
      "ORDER_PAYMENT_MANUAL_DISABLED",
    );
    current = await advanceFulfillment(page, current, "PICKING");
    current = await advanceFulfillment(page, current, "PACKED");
    current = await advanceFulfillment(page, current, "SHIPPED");
    current = await advanceFulfillment(page, current, "DELIVERED");
    expect(current.status).toBe("PROCESSING");
    expect(current.paymentStatus).toBe("UNPAID");
    expect(current.fulfillmentStatus).toBe("DELIVERED");

    const noteKey = requestKey("internal-note-primary");
    const note = await browserApi<Order>(
      page,
      `/api/admin/orders/${current.id}/notes`,
      {
        method: "POST",
        idempotencyKey: noteKey,
        body: {
          visibility: "INTERNAL",
          content: "E2E_PHASE07_INTERNAL_NOTE",
          idempotencyKey: noteKey,
        },
      },
    );
    expect(note.status).toBe(200);
    expect(note.body.success).toBe(true);
    primaryOrder = current;
  });

  test("keeps internal operational notes out of the customer order projection", async ({
    page,
  }) => {
    expect(primaryOrder).not.toBeNull();
    await login(page, ORDER_E2E_ACTORS.CUSTOMER, "/account/orders");
    const result = requireOrder(
      await browserApi<Order>(
        page,
        `/api/store/orders/${encodeURIComponent(primaryOrder!.orderNumber)}`,
      ),
      200,
    );
    expect(result.status).toBe("PROCESSING");
    expect(JSON.stringify(result)).not.toContain("E2E_PHASE07_INTERNAL_NOTE");
  });

  test("allows an authorized manager to create and cancel an eligible assisted order", async ({
    page,
  }) => {
    await login(page, ORDER_E2E_ACTORS.ORDER_MANAGER, "/admin/orders/create");
    const form = page.getByTestId("admin-order-create");
    await expect(form).toBeVisible();
    await expect(
      form.getByRole("button", { name: /^ثبت سفارش$/ }),
    ).toBeDisabled();
    await form
      .getByPlaceholder("cuid مشتری")
      .fill(ORDER_E2E_ACTORS.CUSTOMER.id);
    await form.locator("select").nth(1).selectOption("PICKUP");
    await form.getByPlaceholder("cuid شعبه").fill(ORDER_E2E_FIXTURES.branch.id);
    await form.getByPlaceholder("cuid مدل").fill(ORDER_E2E_FIXTURES.variant.id);

    const [createResponse] = await Promise.all([
      page.waitForResponse(
        (response) =>
          new URL(response.url()).pathname === "/api/admin/orders" &&
          response.request().method() === "POST",
      ),
      form.getByRole("button", { name: /^ثبت سفارش$/ }).click(),
    ]);
    const created = await requireOrderResponse(createResponse, 201);
    await expect(page).toHaveURL(new RegExp(`/admin/orders/${created.id}$`));
    await expect(page.getByTestId("admin-order-detail")).toBeVisible();

    await page.getByRole("button", { name: /^لغو سفارش$/ }).click();
    const cancelDialog = page.getByRole("dialog");
    await expect(cancelDialog).toBeVisible();
    await cancelDialog
      .getByPlaceholder("برای نمونه: CUSTOMER_REQUEST")
      .fill("E2E_OPERATOR_CANCELLED");
    const [cancelResponse] = await Promise.all([
      page.waitForResponse(
        (response) =>
          new URL(response.url()).pathname ===
            `/api/admin/orders/${created.id}/cancel` &&
          response.request().method() === "POST",
      ),
      cancelDialog.getByRole("button", { name: /تأیید لغو سفارش/ }).click(),
    ]);
    const cancelled = await requireOrderResponse(cancelResponse, 200);
    expect(cancelled.status).toBe("CANCELLED");
    expect(cancelled.allocationStatus).toBe("RELEASED");
  });

  test("keeps the customer and administrative order surfaces keyboard-operable and free of core axe violations", async ({
    page,
  }) => {
    await login(page, ORDER_E2E_ACTORS.CUSTOMER, "/account/orders");
    await expect(page.getByTestId("customer-order-list")).toBeVisible();
    await expect(
      new AxeBuilder({ page })
        .include('[data-testid="customer-order-list"]')
        .analyze(),
    ).resolves.toMatchObject({ violations: [] });

    await login(page, ORDER_E2E_ACTORS.ORDER_MANAGER, "/admin/orders");
    await expect(page.getByTestId("admin-order-list")).toBeVisible();
    await expect(
      new AxeBuilder({ page })
        .include('[data-testid="admin-order-list"]')
        .analyze(),
    ).resolves.toMatchObject({ violations: [] });
    await page.getByRole("link", { name: primaryOrder!.orderNumber }).focus();
    await expect(
      page.getByRole("link", { name: primaryOrder!.orderNumber }),
    ).toBeFocused();
  });
});
