import { PERMISSIONS, type Permission } from "@/server/security/permissions";

export type SystemRoleDefinition = {
  code: string;
  name: string;
  description: string;
  permissions: readonly Permission[];
};

const allPermissions = [...PERMISSIONS] as const;

export const SYSTEM_ROLES: readonly SystemRoleDefinition[] = [
  {
    code: "SUPER_ADMIN",
    name: "Super Admin",
    description: "Full platform administration.",
    permissions: allPermissions,
  },
  {
    code: "ADMIN",
    name: "Administrator",
    description: "Operational administration across all modules.",
    permissions: allPermissions,
  },
  {
    code: "BUSINESS_OWNER",
    name: "Business Owner",
    description: "Executive visibility and business governance.",
    permissions: [
      "dashboard.read",
      "users.read",
      "roles.read",
      "permissions.read",
      "settings.read",
      "audit.read",
      "reports.read",
    ],
  },
  {
    code: "CATALOG_MANAGER",
    name: "Catalog Manager",
    description:
      "Governed Apple product, taxonomy, media, specification, warranty, and import preparation.",
    permissions: [
      "dashboard.read",
      "products.read",
      "products.create",
      "products.update",
      "products.delete",
      "brands.read",
      "brands.create",
      "brands.update",
      "brands.delete",
      "categories.read",
      "categories.create",
      "categories.update",
      "categories.delete",
      "attributes.read",
      "attributes.create",
      "attributes.update",
      "attributes.delete",
      "warranties.read",
      "warranties.create",
      "warranties.update",
      "warranties.delete",
      "product-imports.read",
      "product-imports.create",
      "media.read",
      "media.create",
    ],
  },
  {
    code: "CATALOG_APPROVER",
    name: "Catalog Approver",
    description:
      "Independent approval of reviewed, publication-ready catalog products.",
    permissions: [
      "dashboard.read",
      "products.read",
      "products.publish",
      "brands.read",
      "categories.read",
      "attributes.read",
      "warranties.read",
      "product-imports.read",
      "audit.read",
    ],
  },
  {
    code: "INVENTORY_MANAGER",
    name: "Inventory Manager",
    description:
      "Cross-branch inventory governance, stock movements, warehouse setup, and tracked-device oversight.",
    permissions: [
      "dashboard.read",
      "products.read",
      "branches.read",
      "branches.create",
      "branches.update",
      "warehouses.read",
      "warehouses.create",
      "warehouses.update",
      "inventory.read",
      "inventory.receive",
      "inventory.adjust",
      "inventory.transfer",
      "inventory.reserve",
      "inventory.release",
      "inventory.policy.update",
      "devices.read",
      "devices.manage",
      "audit.read",
      "reports.read",
    ],
  },
  {
    code: "BRANCH_MANAGER",
    name: "Branch Manager",
    description:
      "Branch-scoped operations, including controlled stock movements, order confirmation, allocation, fulfillment, and payment visibility.",
    permissions: [
      "dashboard.read",
      "users.read",
      "products.read",
      "branches.read",
      "warehouses.read",
      "inventory.read",
      "inventory.receive",
      "inventory.adjust",
      "inventory.transfer",
      "inventory.reserve",
      "inventory.release",
      "devices.read",
      "orders.read",
      "orders.create_admin",
      "orders.confirm",
      "orders.cancel",
      "orders.allocate",
      "orders.fulfill",
      "orders.view_customer_pii",
      "orders.add_internal_note",
      "payments.read",
      "crm.read",
      "reports.read",
    ],
  },
  {
    code: "READ_ONLY_USER",
    name: "Read-only User",
    description:
      "Inventory and device visibility without any mutation permission.",
    permissions: [
      "dashboard.read",
      "products.read",
      "branches.read",
      "warehouses.read",
      "inventory.read",
      "devices.read",
    ],
  },
  {
    code: "NO_PERMISSION_USER",
    name: "No-permission User",
    description:
      "An active administrative identity with no effective permissions.",
    permissions: [],
  },
  {
    code: "SALES_STAFF",
    name: "Sales Staff",
    description: "Branch sales and CRM operations.",
    permissions: [
      "dashboard.read",
      "products.read",
      "orders.read",
      "orders.create_admin",
      "orders.add_internal_note",
      "crm.read",
    ],
  },
  {
    code: "WAREHOUSE_STAFF",
    name: "Warehouse Staff",
    description:
      "Branch-scoped physical stock operations without branch or policy administration.",
    permissions: [
      "dashboard.read",
      "products.read",
      "warehouses.read",
      "inventory.read",
      "inventory.receive",
      "inventory.adjust",
      "inventory.transfer",
      "inventory.reserve",
      "inventory.release",
      "devices.read",
    ],
  },
  {
    code: "FINANCE_STAFF",
    name: "Finance Staff",
    description: "Finance, order, and payment review.",
    permissions: [
      "dashboard.read",
      "orders.read",
      "orders.view_financials",
      "orders.cancel_after_payment",
      "orders.audit.read",
      "payments.read",
      "payments.read_financial",
      "finance.read",
      "reports.read",
    ],
  },
  {
    code: "FINANCE_MANAGER",
    name: "Finance Manager",
    description:
      "Controlled payment verification, reconciliation, refunds, and financial evidence.",
    permissions: [
      "dashboard.read",
      "orders.read",
      "orders.view_financials",
      "orders.cancel_after_payment",
      "orders.audit.read",
      "payments.read",
      "payments.read_financial",
      "payments.verify",
      "payments.reconcile",
      "payments.refund",
      "payments.audit.read",
      "payments.provider_reference.read",
      "finance.read",
      "reports.read",
    ],
  },
  {
    code: "ORDER_MANAGER",
    name: "Order Manager",
    description: "Cross-branch order lifecycle governance.",
    permissions: [
      "dashboard.read",
      "products.read",
      "branches.read",
      "warehouses.read",
      "orders.read",
      "orders.create_admin",
      "orders.update",
      "orders.confirm",
      "orders.cancel",
      "orders.allocate",
      "orders.fulfill",
      "orders.view_financials",
      "orders.view_customer_pii",
      "orders.add_internal_note",
      "orders.audit.read",
      "payments.read",
      "reports.read",
    ],
  },
  {
    code: "BRANCH_OPERATOR",
    name: "Branch Operator",
    description: "Branch-scoped order fulfillment and internal notes.",
    permissions: [
      "dashboard.read",
      "products.read",
      "orders.read",
      "orders.create_admin",
      "orders.fulfill",
      "orders.add_internal_note",
    ],
  },
  {
    code: "FINANCE_OPERATOR",
    name: "Finance Operator",
    description:
      "Financial order review and paid-order cancellation authority.",
    permissions: [
      "dashboard.read",
      "orders.read",
      "orders.view_financials",
      "orders.cancel_after_payment",
      "orders.audit.read",
      "finance.read",
      "reports.read",
    ],
  },
  {
    code: "READ_ONLY_AUDITOR",
    name: "Read-only Auditor",
    description: "Read-only operational and audit access.",
    permissions: [
      "dashboard.read",
      "orders.read",
      "orders.audit.read",
      "payments.read",
      "payments.audit.read",
      "audit.read",
      "reports.read",
    ],
  },
  {
    code: "AUDITOR",
    name: "Payment Auditor",
    description: "Read-only payment lifecycle and audit evidence.",
    permissions: [
      "dashboard.read",
      "orders.read",
      "payments.read",
      "payments.audit.read",
      "audit.read",
      "reports.read",
    ],
  },
  {
    code: "SUPPORT_STAFF",
    name: "Support Staff",
    description: "Customer support and notification handling.",
    permissions: [
      "dashboard.read",
      "users.read",
      "crm.read",
      "notifications.read",
      "notifications.update",
    ],
  },
  {
    code: "CUSTOMER",
    name: "Customer",
    description: "Customer account role; it does not grant admin access.",
    permissions: ["orders.read_own", "orders.create"],
  },
];

export const permissionDefinitions = PERMISSIONS.map((code) => ({
  code,
  group: code.split(".")[0] ?? "system",
  description: `${code} permission`,
}));
